# Reading Data Templates

## 5 template Digit 1 - (1a,1b,1c,1d,1e)

In [125]:
#Template 1a
list_1a = []
with open("isolated_digits/3/1/ac_1.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_1a.append(a)
        
list_1a1 = []
for i in range(len(list_1a)):
    b = list_1a[i][0].split()
    list_1a1.append(b)
    
template_1a= []
for i in range(1,len(list_1a1)):
    data_1a= [float(x) for x in list_1a1[i]]
    template_1a.append(data_1a)
    
#########################################################################################  

# Template 1b 
list_1b = []
with open("isolated_digits/3/1/ag_1.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_1b.append(a)
        
list_1b1 = []
for i in range(len(list_1b)):
    b = list_1b[i][0].split()
    list_1b1.append(b)
    
template_1b= []
for i in range(1,len(list_1b1)):
    data_1b= [float(x) for x in list_1b1[i]]
    template_1b.append(data_1b)

#########################################################################################  

# Template 1c
list_1c = []
with open("isolated_digits/3/1/ai_1.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_1c.append(a)
        
list_1c1 = []
for i in range(len(list_1c)):
    b = list_1c[i][0].split()
    list_1c1.append(b)
    
template_1c= []
for i in range(1,len(list_1c1)):
    data_1c= [float(x) for x in list_1c1[i]]
    template_1c.append(data_1c)

    

#########################################################################################  

# Template 1d
list_1d = []
with open("isolated_digits/3/1/an_1.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_1d.append(a)
        
list_1d1 = []
for i in range(len(list_1d)):
    b = list_1d[i][0].split()
    list_1d1.append(b)
    
template_1d= []
for i in range(1,len(list_1d1)):
    data_1d= [float(x) for x in list_1d1[i]]
    template_1d.append(data_1d)
    

#########################################################################################  

# Template 1e
list_1e = []
with open("isolated_digits/3/1/bh_1.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_1e.append(a)
        
list_1e1 = []
for i in range(len(list_1e)):
    b = list_1e[i][0].split()
    list_1e1.append(b)
    
template_1e= []
for i in range(1,len(list_1e1)):
    data_1e= [float(x) for x in list_1e1[i]]
    template_1e.append(data_1e)

## Template Digit 2 - 2a,2b,2c,2d,2e


In [114]:
#Template 2a
list_2a = []
with open("isolated_digits/3/2/ac_2.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_2a.append(a)
        
list_2a1 = []
for i in range(len(list_2a)):
    b = list_2a[i][0].split()
    list_2a1.append(b)
    
template_2a= []
for i in range(1,len(list_2a1)):
    data_2a= [float(x) for x in list_2a1[i]]
    template_2a.append(data_2a)
    
#########################################################################################  

# Template 2b 
list_2b = []
with open("isolated_digits/3/2/ag_2.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_2b.append(a)
        
list_2b1 = []
for i in range(len(list_2b)):
    b = list_2b[i][0].split()
    list_2b1.append(b)
    
template_2b= []
for i in range(1,len(list_2b1)):
    data_2b= [float(x) for x in list_2b1[i]]
    template_2b.append(data_2b)

#########################################################################################  

# Template 2c
list_2c = []
with open("isolated_digits/3/2/ai_2.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_2c.append(a)
        
list_2c1 = []
for i in range(len(list_2c)):
    b = list_2c[i][0].split()
    list_2c1.append(b)
    
template_2c= []
for i in range(1,len(list_2c1)):
    data_2c= [float(x) for x in list_2c1[i]]
    template_2c.append(data_2c)

    

#########################################################################################  

# Template 2d
list_2d = []
with open("isolated_digits/3/2/an_2.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_2d.append(a)
        
list_2d1 = []
for i in range(len(list_2d)):
    b = list_2d[i][0].split()
    list_2d1.append(b)
    
template_2d= []
for i in range(1,len(list_2d1)):
    data_2d= [float(x) for x in list_2d1[i]]
    template_2d.append(data_2d)
    

#########################################################################################  

# Template 2e
list_2e = []
with open("isolated_digits/3/2/bh_2.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_2e.append(a)
        
list_2e1 = []
for i in range(len(list_2e)):
    b = list_2e[i][0].split()
    list_2e1.append(b)
    
template_2e= []
for i in range(1,len(list_2e1)):
    data_2e= [float(x) for x in list_2e1[i]]
    template_2e.append(data_2e)

## Template Digit Z - Za, Zb,Zc,Zd,Ze

In [131]:
#Template za
list_za = []
with open("isolated_digits/3/z/ac_z.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_za.append(a)
        
list_za1 = []
for i in range(len(list_za)):
    b = list_za[i][0].split()
    list_za1.append(b)
    
template_za= []
for i in range(1,len(list_za1)):
    data_za= [float(x) for x in list_za1[i]]
    template_za.append(data_za)
    
#########################################################################################  

# Template zb 
list_zb = []
with open("isolated_digits/3/z/ag_z.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_zb.append(a)
        
list_zb1 = []
for i in range(len(list_zb)):
    b = list_zb[i][0].split()
    list_zb1.append(b)
    
template_zb= []
for i in range(1,len(list_zb1)):
    data_zb= [float(x) for x in list_zb1[i]]
    template_zb.append(data_zb)

#########################################################################################  

# Template 2c
list_zc = []
with open("isolated_digits/3/z/ai_z.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_zc.append(a)
        
list_zc1 = []
for i in range(len(list_zc)):
    b = list_zc[i][0].split()
    list_zc1.append(b)
    
template_zc= []
for i in range(1,len(list_zc1)):
    data_zc= [float(x) for x in list_zc1[i]]
    template_zc.append(data_zc)

    

#########################################################################################  

# Template 2d
list_zd = []
with open("isolated_digits/3/z/an_z.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_zd.append(a)
        
list_zd1 = []
for i in range(len(list_zd)):
    b = list_zd[i][0].split()
    list_zd1.append(b)
    
template_zd= []
for i in range(1,len(list_zd1)):
    data_zd= [float(x) for x in list_zd1[i]]
    template_zd.append(data_zd)
    

#########################################################################################  

# Template 2e
list_ze = []
with open("isolated_digits/3/z/bh_z.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_ze.append(a)
        
list_ze1 = []
for i in range(len(list_ze)):
    b = list_ze[i][0].split()
    list_ze1.append(b)
    
template_ze= []
for i in range(1,len(list_ze1)):
    data_ze= [float(x) for x in list_ze1[i]]
    template_ze.append(data_ze)

In [118]:
list_t = []
with open("isolated_digits/3/z/cl_z.mfcc") as f :
    for line in f:
        a = [line.strip()]
#         print(line.strip())
        list_t.append(a)
        
list_t1 = []
for i in range(len(list_t)):
    b = list_t[i][0].split()
    list_t1.append(b)
    
Test_t= []
for i in range(1,len(list_t1)):
    data_t= [float(x) for x in list_t1[i]]
    Test_t.append(data_t)

In [5]:
def ED(X1,Y1):
    
  dist = np.sqrt(np.dot(X1-Y1,X1-Y1))
  return dist



In [106]:
import numpy as np

# a = np.array([1,2,3,4])
# b = np.array([5,6,18,91])

a = np.array(template_1a)
b = np.array(template_1b)


def DTW(Ref_sig, Test_sig):
    n = len(Ref_sig)
    m = len(Test_sig)
    
    cost_matrix = np.zeros((n+1,m+1))
        
    for j in range(m+1):
        cost_matrix[0,j] = np.inf
    
    for i in range(n+1):
        cost_matrix[i,0] = np.inf

        
    cost_matrix[0,0] = 0
    
    distance = np.zeros((n,m))
    
    for i in range(0,n):
     
     for j in range(0,m):
            
            dist = np.linalg.norm(Test_sig[j]-Ref_sig[i])
            distance[i,j] = dist
            
    print(distance)
    path_matrix = np.zeros((n,m))
    for i in range(1,n+1):
        
        for j in range(1,m+1):
            min_dis = min(cost_matrix[i-1,j-1]  ,cost_matrix[i,j-1], cost_matrix[i-1,j]) 
            
            cost_matrix[i,j] = distance[i-1,j-1]+ min_dis
            
            if min_dis ==cost_matrix[i-1,j-1]:
                 path_matrix[i-1,j-1]=0 
            elif min_dis ==cost_matrix[i,j-1]:
                path_matrix[i-1,j-1]=1
            else:
                path_matrix[i-1,j-1]=2
                
            
            #match(i-1,j-1)
            #deletion(i,j-1)
            #insertion(i-1,j)
            
            
    i = n-1
    j = m-1
    path=[]
    while i >=0 or j>=0:
        path.append((i,j))
        check = path_matrix[i,j]
        if check ==0:
            i=i-1
            j=j-1
        elif check ==1:
            j=j-1
        else:
            i = i-1
    print(cost_matrix)
    print(path_matrix)
    print(path)
    

    
    return cost_matrix[n,m]
    
DTW(a,b)
            
    

[[2.46791981 3.52724807 3.07407926 ... 3.97880582 3.76603014 3.601295  ]
 [3.40415593 3.54230244 3.62817611 ... 4.39912894 4.73498023 4.21489382]
 [5.21913482 4.67827416 4.74721426 ... 4.8993023  5.95550289 6.1845913 ]
 ...
 [3.68380521 3.48456282 3.23176431 ... 2.78093552 3.24499425 3.07475551]
 [5.08776887 4.50589714 4.96503198 ... 4.88550435 5.20274508 4.98967064]
 [4.96675134 4.79266241 5.11032922 ... 5.21233756 5.12246732 4.874901  ]]
[[  0.                  inf          inf ...          inf          inf
           inf]
 [         inf   2.46791981   5.99516788 ... 835.6911777  839.45720784
  843.05850284]
 [         inf   5.87207574   6.01022225 ... 780.57248059 785.30746082
  789.52235463]
 ...
 [         inf 729.38231884 699.27645592 ... 426.70540672 427.70375945
  430.77851496]
 [         inf 734.47008771 703.78235306 ... 430.76308134 431.9081518
  432.69343009]
 [         inf 739.43683904 708.57501547 ... 435.46459608 435.88554866
  436.78305281]]
[[0. 1. 1. ... 1. 1. 1.]
 [2.

436.7830528060439

In [107]:
from fastdtw import fastdtw
from scipy.spatial.distance import euclidean

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[18,91]])

distance1, path = fastdtw(a, b)

print(distance1)
print(path)

1830.6398292124006
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 15), (17, 16), (18, 17), (19, 18), (20, 19), (21, 20), (22, 21), (23, 22), (24, 23), (24, 24), (24, 25), (24, 26), (24, 27), (24, 28), (24, 29), (25, 30), (26, 31), (27, 32), (28, 33), (28, 34), (28, 35), (28, 36), (29, 37), (30, 38), (31, 39), (32, 40), (33, 41), (34, 42), (35, 43), (36, 44), (37, 45), (38, 46), (38, 47), (39, 48), (40, 49), (41, 50), (42, 51), (43, 52), (43, 53), (44, 54), (45, 55), (46, 56), (47, 57), (48, 58), (49, 59), (50, 60), (51, 61), (52, 62), (53, 63), (54, 64), (55, 65), (56, 66), (57, 67), (58, 68), (59, 69), (60, 70), (61, 71), (62, 72), (63, 73), (64, 74), (65, 75), (66, 76), (67, 77), (68, 78), (69, 79), (70, 79), (71, 80), (72, 81), (73, 82), (74, 83)]


In [84]:
x.shape[0]

2

## Average score of Digit 1 

In [127]:
a1 = np.array(template_1a)
b1 = np.array(Test_t)
cost1 = DTW(a1,b1)

a2 = np.array(template_1b)
b2 = np.array(Test_t)
cost2 = DTW(a2,b2)

a3 = np.array(template_1c)
b3 = np.array(Test_t)
cost3 = DTW(a3,b3)

a4 = np.array(template_1d)
b4 = np.array(Test_t)
cost4 = DTW(a4,b4)

a5 = np.array(template_1e)
b5 = np.array(Test_t)
cost5 = DTW(a5,b5)

Avg_digit1 = (cost1+cost2+cost2+cost4+cost5)/5



[[3.37500474 4.29739311 3.6499921  ... 6.62665344 6.76761837 4.96507181]
 [4.04329209 3.65383981 4.30665145 ... 5.89550039 6.05820701 4.66759201]
 [4.61848984 3.66169494 5.35259631 ... 4.93412773 4.9414761  4.32808449]
 ...
 [4.49702245 3.86933258 3.85530378 ... 6.08605899 6.22637342 4.86035001]
 [5.99251877 4.80736096 5.72131682 ... 6.58594243 6.52772501 5.79732913]
 [5.75188266 5.38930343 5.4644794  ... 6.07030068 6.78133705 5.14089579]]
[[   0.                   inf           inf ...           inf
            inf           inf]
 [          inf    3.37500474    7.67239784 ... 1600.91487474
  1607.68249311 1612.64756492]
 [          inf    7.41829683    7.02884454 ... 1516.97756735
  1523.03577435 1527.70336636]
 ...
 [          inf  696.57717935  647.01250321 ... 1123.62916454
  1125.65904871 1127.54957422]
 [          inf  702.56969812  651.81986417 ... 1127.4221145
  1130.15688955 1131.45637784]
 [          inf  708.32158078  657.2091676  ... 1130.83559752
  1134.20345156 1135.2977

[[3.09015025 3.8336434  3.16495204 ... 6.273528   7.09624773 5.44402091]
 [3.43730361 4.45376894 3.85012177 ... 6.39853711 7.56515049 5.55762892]
 [4.70052897 3.79471422 4.39664709 ... 6.97605437 7.1711693  6.39781903]
 ...
 [4.50604515 4.6706808  4.98100372 ... 4.7526197  6.09351479 4.46224992]
 [5.30347328 3.80050703 4.98550081 ... 5.79839879 5.92431994 5.15152568]
 [4.27160835 4.61732009 4.73096277 ... 4.29028053 5.58193754 3.4602622 ]]
[[   0.                   inf           inf ...           inf
            inf           inf]
 [          inf    3.09015025    6.92379365 ... 1526.23802631
  1533.33427404 1538.77829494]
 [          inf    6.52745387    7.54391919 ... 1518.42550568
  1525.99065616 1531.54828509]
 ...
 [          inf  950.07535807  892.61236119 ... 1114.42014379
  1117.91887018 1120.01456412]
 [          inf  955.37883134  896.41286822 ... 1117.75370711
  1120.34446372 1123.07039587]
 [          inf  959.6504397   901.03018832 ... 1118.18055653
  1123.33564464 1123.804

## Average score of digit 2

In [128]:
a1 = np.array(template_2b)
b1 = np.array(Test_t)
cost1 = DTW(a1,b1)

a2 = np.array(template_2b)
b2 = np.array(Test_t)
cost2 = DTW(a2,b2)

a3 = np.array(template_2c)
b3 = np.array(Test_t)
cost3 = DTW(a3,b3)

a4 = np.array(template_2d)
b4 = np.array(Test_t)
cost4 = DTW(a4,b4)

a5 = np.array(template_2e)
b5 = np.array(Test_t)
cost5 = DTW(a5,b5)

Avg_digit2 = (cost1+cost2+cost2+cost4+cost5)/5

[[4.93423887 5.50070025 5.60622585 ... 5.79869905 6.02340661 4.73151998]
 [3.71300406 4.19544264 4.31764402 ... 5.72396277 5.39285601 4.21426174]
 [4.24242225 5.08817771 5.13338796 ... 4.85605644 5.65802366 3.55249841]
 ...
 [6.03468574 5.83796427 6.45841063 ... 4.8778937  5.18363615 4.5836314 ]
 [5.91455342 6.50184554 6.51724354 ... 5.91195615 6.2463155  5.27789035]
 [5.64004474 6.70897813 6.48115332 ... 5.73804416 6.59010177 4.95878178]]
[[   0.                   inf           inf ...           inf
            inf           inf]
 [          inf    4.93423887   10.43493912 ... 1550.25949387
  1556.28290047 1561.01442045]
 [          inf    8.64724293    9.12968151 ... 1508.38431008
  1513.77716609 1517.99142782]
 ...
 [          inf  850.23550815  813.74567265 ... 1086.3193242
  1091.42352584 1095.12132598]
 [          inf  856.15006156  820.24751819 ... 1087.70484476
  1092.5656397  1096.70141619]
 [          inf  861.7901063   826.95649632 ... 1089.03918978
  1094.29494653 1097.5244

[[3.78345089 5.13515983 4.93485315 ... 4.58173961 5.92524222 4.32586202]
 [4.47697964 5.36824558 5.44853855 ... 4.63312057 6.14245682 4.70840926]
 [4.12193983 4.80091463 4.69682833 ... 4.64643766 5.24887903 4.36228382]
 ...
 [3.70776414 4.39363779 3.81832166 ... 4.44099659 4.9125041  3.2396299 ]
 [4.83629391 5.36535632 5.26649561 ... 4.47393759 4.93296741 3.95153784]
 [7.48428801 7.14615386 7.92678802 ... 4.44791469 4.96945344 5.25690181]]
[[   0.                   inf           inf ...           inf
            inf           inf]
 [          inf    3.78345089    8.91861071 ... 1442.77262024
  1448.69786246 1453.02372448]
 [          inf    8.26043052    9.15169646 ... 1423.44462775
  1429.58708457 1434.29549383]
 ...
 [          inf 1052.67599546 1010.39235806 ... 1059.51252799
  1063.53268136 1065.55891375]
 [          inf 1057.51228937 1015.75771438 ... 1063.37148029
  1064.44549539 1067.4842192 ]
 [          inf 1064.99657738 1022.90386824 ... 1066.7935401
  1068.34093373 1069.7023

## Average score of digit z

In [1]:
a1 = np.array(template_zb)
b1 = np.array(Test_t)
cost1 = DTW(a1,b1)

a2 = np.array(template_zb)
b2 = np.array(Test_t)
cost2 = DTW(a2,b2)

a3 = np.array(template_zc)
b3 = np.array(Test_t)
cost3 = DTW(a3,b3)

a4 = np.array(template_zd)
b4 = np.array(Test_t)
cost4 = DTW(a4,b4)

a5 = np.array(template_ze)
b5 = np.array(Test_t)
cost5 = DTW(a5,b5)

Avg_digitz = (cost1+cost2+cost2+cost4+cost5)/5



NameError: name 'np' is not defined

In [134]:
print("Average score of digit 1", Avg_digit1)
print("Average score of digit 2", Avg_digit2)
print("Average score of digit z", Avg_digitz)

Average score of digit 1 1162.4470986438098
Average score of digit 2 1053.9613257118533
Average score of digit z 932.9849654672987
